[package]
name = "keyboard-dimm"
version = "0.1.0"
edition = "2021"
authors = ["David Marco"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input = "0.7"
libc = "0.2"
notify = "4.0"
